type:
  local:
    fluent:
      root:
      version: "252"
      dimension: 3
      precision: double
    resources:
      cpus: 4
      memory: 4G

  m3:
    fluent:
      root:
      version: "252"
      dimension: 3
      precision: double
    resources:
      cpus:
      memory:
    scheduler:
      partition: normal
      walltime: "01:00:00"

  mock:
    fluent:
      root: mockfluent
      version: "000"
      dimension: 3
      precision: double
    resources:
      cpus: 2
      memory: 1G
