environment: local

type:
  local:
    memory: 1
    processor_count: 4

    ansys:
      version: "252"
      root: "C:/Program Files/ANSYS Inc/v252"
  
  hpc:
    memory:
    processor_count:

    ansys:
      version: "252"
      root: "/apps/ansys_inc/v252"

  
  mock:
    memory: 1
    processor_count: 2

    ansys:
      version: "000"
      root: "mockfluent"